version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: leaveee-postgres
    ports:
      - "5600:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: leave_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: leaveee-backend
    ports:
      - "3600:3600"
    depends_on:
      - postgres
    volumes:
      - ./Backend/uploads:/app/uploads
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin321
      - DB_NAME=leave_management
      - DB_PORT=5432

  employee-leave:
    build: ./employee-leave
    container_name: employee-leaveee
    ports:
      - "8600:80"
    depends_on:
      - backend

  hr-leave:
    build: ./hr-leave
    container_name: hr-leaveee
    ports:
      - "8601:80"
    depends_on:
      - backend

volumes:
  pgdata:

